  class TimeTexts{
  // These lists are used to get the correct time
  // as string. Eg. if DateTime().hours returns a 
  // value between 0 and 23, so the corresponding 
  // value as string can be found from [hours] list
  // at that very index.
  
  static final List<String> minutes = [
    "",
    "one",
    "two",
    "three",
    "four",
    "five",
    "six",
    "seven",
    "eight",
    "nine",
    "ten",
    "eleven",
    "twelve",
    "thirteen",
    "fourteen",
    "quarter",
    "sixteen",
    "seventeen",
    "eighteen",
    "nineteen",
    "twenty",
    "twenty-one",
    "twenty-two",
    "twenty-three",
    "twenty-four",
    "twenty-five",
    "twenty-six",
    "twenty-seven",
    "twenty-eight",
    "twenty-nine",
    "half",
    "twenty-nine",
    "twenty-eight",
    "twenty-seven",
    "twenty-six",
    "twenty-five",
    "twenty-four",
    "twenty-three",
    "twenty-two",
    "twenty-one",
    "twenty",
    "nineteen",
    "eighteen",
    "seventeen",
    "sixteen",
    "quarter",
    "fourteen",
    "thirteen",
    "twelve",
    "eleven",
    "ten",
    "nine",
    "eight",
    "seven",
    "six",
    "five",
    "four",
    "three",
    "two",
    "one",
  ];

  static final List<String> hours = [
    "midnight",
    "one",
    "two",
    "three",
    "four",
    "five",
    "six",
    "seven",
    "eight",
    "nine",
    "ten",
    "eleven",
    "twelve",
    "one",
    "two",
    "three",
    "four",
    "five",
    "six",
    "seven",
    "eight",
    "nine",
    "ten",
    "eleven",
  ];
}